---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gremlin-demo-cluster
  region: us-east-2
  version: "1.18"

managedNodeGroups:
  - name: managed-ng-public
    instanceType: m5.large
    minSize: 2
    desiredCapacity: 2
    maxSize: 2
    availabilityZones: ["us-east-2a", "us-east-2b"]
    volumeSize: 30
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    ssh:
      allow: true
      publicKeyName: gremlin-demo-key
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
